# -*- coding: utf-8 -*-
"""planes_gobierno_sanmartin2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ee27eknfnPdqWvOmt2hh4orhwukGSnKd

#### Nube de palabras 

> Usando matplotlib

En esta oportunidad realizaremos un analisis de las palbras expuestas en los diferentes planes de gobierno presentados al JNE, para las elecciones municipales y Regionales del 2022, para el Gobierno Regional de San Martin 2022
"""

# importamos las librerias que vamos a utilizar
import pandas as pd
import numpy as np
import io
import matplotlib.pyplot as plt
import seaborn as sns
import nltk 
nltk.download('book')
from nltk.book import *
from nltk.corpus import stopwords
from wordcloud import WordCloud

"""Adjuntamos nuestro archivo a analizar"""

from google.colab import files 
uploaded = files.upload()

"""los mencionados planes de gobirnos se encuentran publicados en la pagina oficial del JNE, de donde su pueden descarar en formato pdf, tendraimmos que convertirlo a CSV y luego subirlo."""

# visualizamos nuestros datos
df = pd.read_csv(io.BytesIO(uploaded["plangobiernogrundel.csv"]))
df

df.head()

"""Damos formato a nuestros datos, modificando las columnas, eliminado los datos vacios, NaN y guardando en nuevo dataframe que es donde lo vamos a utilizar."""

texto= df.rename(columns={'Firmado Digitalmente por:':'texto'})
texto.columns

# visualizamos nuestros datos
texto.head()

df.shape

texto1= texto.dropna()
texto1.head()

texto1.shape

"""## stopword, nos ofrece  la oportunidad de quitar de nuestro texto, las palabras que no presentan valor para nuestra nube de palabras, como son, proposiciones, articulos, conjuciones, etc."""

print(stopwords.words('spanish'))

"""nuestro texto, lo agregamos a uns arreglo, en donde podemos contar nuestras palabras para poder mapearlos"""

textos_plan = ''
for row in texto1['texto']: 
    textos_plan = textos_plan + ' ' + row

"""en nuestra variable, que designaremos como "y", adjuntamos nuestras palabras excluidas, en stopwords del idioma español, y tambien adjuntamos a esta lista, palbras que podrian aparecer y que no generarian valor para el sentido de esta visualizacion, como son "'2020','sistema' ,'2021','2022','región','regional','cont','martín','somos','peru','perú','san martín','partido','democrático']"
"""

y = stopwords.words('spanish') + ['2020','sistema' ,'2021','2022','región','regional','cont','martin','somos','peru','perú','partido','democrático']

"""unimos nuestros resultados en nuevo dataframe."""

textos_plan = ' '.join([x for x in textos_plan.strip().lower().split(' ') if x not in y and len(x)>4])

"""Graficamos nuestros resultados"""

wc = WordCloud(background_color= 'white')
wc.generate(textos_plan)
#plt.axis("off")
plt.figure(figsize=(10,10))
plt.imshow(wc, interpolation='bilinear')
plt.show()